---
- name: Add a Single Directory
  include_tasks: createdir.yml
  when:
    - directory_path is defined
    - create_directories is undefined

- name: Add Multiple Directories
  include_tasks: createdir.yml
  loop: "{{ create_directories if create_directories is defined else [] }}"
  loop_control:
    loop_var: directory_item
  vars:
    directory_path: "{{ directory_item.directory_path }}"
    directory_user_owner: "{{ directory_item.directory_user_owner if directory_item.directory_user_owner is defined else undefined }}"
    directory_group_owner: "{{ directory_item.directory_group_owner if directory_item.directory_group_owner is defined else undefined }}"
    directory_mode: "{{ directory_item.directory_mode if directory_item.directory_mode is defined else undefined }}"
  when:
    - create_directories is defined
